apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvel-kata-deployment
  labels:
    app: marvel-kata-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvel-kata-app
  template:
    metadata:
      labels:
        app: marvel-kata-app
    spec:
      containers:
        - name: marvel-kata-app
          image: marvel-kata-k8s
          ports:
            - containerPort: 8080